# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Pe', 'Perro'), ('Ga', 'Gato'), ('Ex', 'Exotico')], default='Pe', max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('edad', models.IntegerField(default=0)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Protectoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='animales',
            name='protectora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protectora.Protectoras'),
        ),
    ]
