# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protectora', '0002_protectoras_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animales',
            name='tipo',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Exotico', 'Exotico')], default='Perro', max_length=10),
        ),
    ]
